### ISSUE TITLE
Difficulty starting the program

### ISSUE THREAD

**Issue by orenpoliva** [m-ama/PyDesigner#291] opened 2022-11-23 00:02 UTC
Hello. I installed the software per the recommended pipeline. However, past this stage there are almost no instructions on how to continue. I'm not a computer expert and was trying to follow the example with the BOND file practice run. I'm running the same line in the terminal with my files instead of the bond files, but keeping getting errors. 
Questions:
Why is the bond_dwi.bval appearing twice (do I need two copies of it)?
What are the topup nii and json files? and how do I get them?
I have data that was generated with MRTRIX3. However, I want o conduct a DKI analysis. What is the pipeline?
Thank you in advance
Oren

**Comment by TheJaeger** [comment] 2022-11-23 16:35
Hi Oren,

Thanks for bringing up the the issues present in our documentation. One of the _.bval_ files should be a _.nii_ files - it's a typo. Converting your files from DICOM to NifTi using [dcm2niix](https://github.com/rordenlab/dcm2niix) will give you all four files (.nii, .bvec, .bval, .json). Alternatively, you can use MRtrix's _mrconvert_ command with the flags `-fslgrad bvecs bvals` and `-json_export file` to also produce those four files.

TOPUP file refers to a reverse phase-encoded B0 volume for susceptibility induced distortion correction. If your primary DKI data was acquired in A>>P phase encoding for example, then your topup acquisition would be a few B0 volumes in P>>A phase. This volume needs to be acquired on the scanner, either before or after the DKI acquisition.

A complete DKI acquisition would have the files DKI.nii, DKI.bval, DKI.bvec, and DKI.json. PyDesigner can process them for you using the syntax

```
pydesigner -s --verbose -o [PATH TO OUTPUT FOLDER] [PATH TO DKI.nii]
```

If you also have a topup acquisition, then simple add it as an input to PyDesigner

```
pydesigner -s --verbose -o [PATH TO OUTPUT FOLDER] [PATH TO DKI.nii] [PATH TO TOPUP.nii]
```

I understand that getting into DKI processing can be overwhelming. We're working on a video tutorial that shows how to process DTI/DKI data with PyDesigner. We can also meet on Teams in the meantime if you'd like me to demonstrate DKI processing.

**Comment by orenpoliva** [comment] 2022-11-23 20:31
Thank you for the prompt response. I converted the files of at least one subject (CDA088) but I keep getting an error message (see the terminal in the screenshot).
BTW is pydesigner also performs group analysis and contrast?
![error](https://user-images.githubusercontent.com/118861965/203640944-3a22e50c-5d98-4089-951c-9c4abb560195.png)

**Comment by TheJaeger** [comment] 2022-11-23 22:33
Hi Oren,

There are a few issues with the command:

1. It appears that PyDesigner cannot find the path to your input NifTi file. The program can't locate CDA088_topup.nii relative to your Docker mount. 
2. There are too many spaces between your input options i.e. `--standard             --output`. Use single-space like `--standard --output`.
3. You're also just processing a TOPUP series which wouldn't produce any dMRI metrics. If you're running EPI correction, the main diffusion acquisition needs to be accompanied with the topup volume.

Assuming that your file path is correct, the full command should be:

```
docker run -it --rm -v ~/Desktop/CDA088:/data dmri/neurodock pydesigner -v --standard --output /data/processed /data/nifti/DKI.nii /data/nifti/CDA088_topup.nii
```

**Comment by orenpoliva** [comment] 2022-11-23 22:38
Thank you. I applied the changes and indeed didn't get errors. instead it simply printed 'v1.0-RC12' and ended the analysis

**Comment by TheJaeger** [comment] 2022-11-23 22:40
I apologize, the flag `-v` print out the version number. The correct flag is `--verbose`. The full commands then is:

```
docker run -it --rm --verbose ~/Desktop/CDA088:/data dmri/neurodock pydesigner -v --standard --output /data/processed /data/nifti/DKI.nii /data/nifti/CDA088_topup.nii
```

**Comment by orenpoliva** [comment] 2022-11-23 22:42
I'm getting: 
unknown flag: --verbose
See 'docker run --help'

**Comment by TheJaeger** [comment] 2022-11-23 22:43
I fixed the command in my comment above. Give it another shot,

**Comment by orenpoliva** [comment] 2022-11-23 22:46
I'm getting the following error:
mrconvert: [ERROR] bvals file must contain 1 row or column only (file "/data/nifti/DKI.bval" has 3)
mrconvert: [ERROR] error importing diffusion gradient table for image "/data/nifti/DKI.nii"
Traceback (most recent call last):
  File "/usr/local/bin/pydesigner", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/designer/pydesigner.py", line 269, in main
    resume=args.resume)
  File "/usr/local/lib/python3.7/dist-packages/designer/preprocessing/util.py", line 477, in cat
    raise Exception('Please use the "--force" flag to '
Exception: Please use the "--force" flag to overwrite existing outputs, or clear the output directory

**Comment by orenpoliva** [comment] 2022-11-23 22:46
Question: As I already did the preprocessing in MRTRIX3, is it possible to skip this stage and go directly to the DKI analysis?

**Comment by orenpoliva** [comment] 2022-11-23 22:50
BTW we have 64 directions. Does that impose any difficulty?

**Comment by TheJaeger** [comment] 2022-11-23 22:55
You can definitely skip preprocessing and jump straight to DKI analysis. You would simply remove any preprocessing flags including `--standard`.

For just DKI metrics, you'd run the following command:

```
docker run -it --rm -v ~/Desktop/CDA088:/data dmri/neurodock pydesigner --output /data/processed /data/nifti/DKI.nii
```

The error above indicates that your _.bvec_ and _.bval_ files may not be formatted correctly. The _.bval_ file should contain just one one row with b-values corresponding to each shell in DWI, whereas the _.bvec_ file should contain 3 rows of gradient vectors. You can attach these two files here for me to check.

PyDesigner won't have any problems with 64 directions. We frequently process 64 direction data here.

**Comment by orenpoliva** [comment] 2022-11-23 22:59
I generated these files
[bvalues.zip](https://github.com/m-ama/PyDesigner/files/10079612/bvalues.zip)
 using this mrtrix command:
mrconvert ~/Desktop/DIPY/ -export_grad_fsl DKI.bval DKI.bvec -json_export DKI.json DKI.nii 

Thank you again for all the support

**Comment by orenpoliva** [comment] 2022-11-23 23:09
Maybe the better question is how do I generate the bvectors/bvalues in the correct format from mrtrix?

**Comment by TheJaeger** [comment] 2022-11-23 23:12
Your _.bvec_ and _.bval_ files are switched. The `mrconvert` command you should have used is:

```
mrconvert ~/Desktop/DIPY/ -export_grad_fsl DKI.bvec DKI.bval -json_export DKI.json DKI.nii
```

For now you can just rename _DKI.bvec_ to _DKI.bval_, and vice versa for the other file.

**Comment by orenpoliva** [comment] 2022-11-23 23:29
Thank you. I had success starting the analysis, and then I got the following error:
ERROR in osqp_setup: KKT matrix factorization.
The problem seems to be non-convex.

PS Is this program just converting images to DKI format, or it can also perform group contrast analysis?

**Comment by orenpoliva** [comment] 2022-11-23 23:33
![Screenshot from 2022-11-23 15-32-21](https://user-images.githubusercontent.com/118861965/203663430-7a4daaab-5407-455c-ad7d-d0a11ac75b99.png)
The following files were generated

**Comment by TheJaeger** [comment] 2022-11-23 23:50
Could you screenshot the error and attach it here? I've never seen it before and having the full error traceback allows me to figure out where and why it's happening. From what I can tell though, it appears that PyDesginer has failed to do a linear least squares fitting at one of the voxels. This could happen when preprocessing is not done properly or when data quality is poor. It would be better to let PyDesigner handle preprocessing and extraction of DTI/DKI parameters from raw diffusion weighted images.

The program doesn't convert your data, it's already a diffusion weighted acquisition. PyDesigner is fitting a diffusion/kurtosis tensor to your input data and deriving commonly studied diffusion metrics (FA, MD, AK, RK, KFA, MK, RK, AK etc.) from the tensors. It enhances the SNR on your DTI/DKI acquisitions and excludes outliers for accurate estimation of dMRI metrics. Group analyses can be performed using other tools like AFQ, TBSS or MRtrix after deriving dMRI metrics from PyDesigner.

**Comment by orenpoliva** [comment] 2022-11-24 01:12
Yes. It was probably the preprocessing. I'll follow up on this analysis after the holiday, and I'll let you know if I need any help.
Happy thanks giving and thank you for the support.
Oren

**Comment by orenpoliva** [comment] 2022-11-28 19:21
Hello again. Thank you for all the help. I've returned to the project, but now I get 
docker: Error response from daemon: Bad response from Docker engine.
See 'docker run --help'.
Any ideas what this mean?

**Comment by orenpoliva** [comment] 2022-11-28 20:29
Update. I got it to work. However, the analysis crashes without any error message (see image). I used a nifti file that was preprocessed in Mrtrix (dwi_denoised_unringed_preproc_unbiased_upsampled.mif), and generated for it the json file. bec and bval were generated from the raw AP.mif file. As you can see in the image, it complained that no brain mask was supplied, but I wasn't sure how to provide it. Any ideas on how to proceed? 
![Screenshot from 2022-11-28 12-25-38](https://user-images.githubusercontent.com/118861965/204374525-2625cbcb-d424-47eb-9dbd-f60f42b2bba8.png)

**Comment by TheJaeger** [comment] 2022-11-28 21:17
This seems to be a memory issue, The next step is AKC correction, which required absurdly large amounts of memory to resample the diffusion tensor at each voxel for 100,000 gradient directions. There are a number of things you can do to alleviate memory strain.

1. Use the `--noakc` flag to bypass AKC tensor correction.
2. Use the `-m` flag to compute a brain mask to limit computations within the brain mask. This will reduce memory footprint.
3. Allocate more space to your swap file to write memory overflow to local disk.

I also recommend installing PyDesigner natively since you're running Ubuntu. Your system is compatible with all requirements. The Docker container was intended for systems like Windows or ARM-based devices that are incompatible with FSL or MRtrix3.

**Comment by orenpoliva** [comment] 2022-11-28 21:25
Thank you. How do I install it locally?

**Comment by TheJaeger** [comment] 2022-11-28 21:28
You begin by installing FSL and MRtrix3 locally. Instructions can be found on each program's page.

Then follow the steps [here](https://pydesigner.readthedocs.io/en/latest/installation/pydesigner.html) to install PyDesigner.

**Comment by orenpoliva** [comment] 2022-11-28 21:30
oh...in that case I already followed this tutorial and have it locally. So, what should I type in the command line, so I won't use the docker?

**Comment by TheJaeger** [comment] 2022-11-28 21:31
Just `pydesigner [OPTIONS] PATH_TO_DWI`.

**Comment by orenpoliva** [comment] 2022-11-28 23:07
Yes. That was very helpful. I got the files, which look fine. But, when look at kFA it appears very noisy (you can't internal structures). Attached are the FA (which seems normal) and the kFA. Is this expected or did something go wrong?
![Screenshot from 2022-11-28 15-04-04](https://user-images.githubusercontent.com/118861965/204399582-26cad1b5-8755-4ee4-9cb8-32300dff4712.png)
![Screenshot from 2022-11-28 15-03-45](https://user-images.githubusercontent.com/118861965/204399606-0acd8a1d-96fc-476d-8210-dd2cb3aca415.png)

**Comment by TheJaeger** [comment] 2022-11-28 23:28
Were both maps windowed from 0 to 1?

**Comment by orenpoliva** [comment] 2022-11-28 23:35
Not in this image. But the images remain identical when we range them from 0 to 1.

BTW what are the wmti files and the DT and KT files in the metrics folder? What is inside the metrics_qc folder?

**Comment by TheJaeger** [comment] 2022-11-29 00:06
It shouldn't like like that then. The KFA map should be similar to FA except in regions susceptible to fiber-crossing. I've attached KFA and FA from a subject that was completely processed using PyDesigner - your maps should look similar. Do other kurtosis measures like MK and RK look plausible? Kurtosis measurements are particularly sensitive to outliers in data, so you may be seeing the results of issues in preprocessing.

![FA](https://user-images.githubusercontent.com/13654344/204406358-bb32b2f4-90be-4184-a606-9818db1e1ff2.png)

![KFA](https://user-images.githubusercontent.com/13654344/204406382-20f1d5e9-1c89-42e5-87ec-bbd490c9985b.png)

DT.nii is the diffusion tensor and KT.nii is the kurtosis tensor. These files are available for users who'd like to run additional MRtrix or DTI-TK analyses. The _metric_qc_ folder contains files to evaluate quality of data. You'll find SNR plots (if preprocessed with PyDesigner), motion plots (if preprocessed with PyDesigner), and outliers from IRLLS outlier detection. Information on files produced by PyDesigner is found at [PyDesigner: List of Output Files](https://pydesigner.readthedocs.io/en/latest/reference/pydesigner_files.html).

White Matter Tract Integrity (WMTI) metrics quantify intra- and extra-axonal components of diffusion, as described in  [E. Fieremans _et al_. Novel White Matter Tract Integrity Metrics Sensitive to Alzheimer Disease Progression](http://www.ajnr.org/content/34/11/2105). However, WMTI has now been superseded by more-accurate compartmental modeling such as [Fiber Ball White Matter Modeling (FBWM)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6064190/).

**Comment by TheJaeger** [comment] 2022-12-06 19:38
Closing the issue because we've managed to run PyDesigner. Discussion on validity of metric maps can be held in [PyDesigner Discussions](https://github.com/m-ama/PyDesigner/discussions).

**Closed** 2022-12-06 19:38 UTC
Labels: documentation
